# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0002_auto_20190128_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
