# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango_app', '0003_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_images')),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Trap', 'trap'), ('Wizard', 'wizard')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
