# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trap', 'Trap'), ('wizard', 'Wizard')], max_length=10),
        ),
    ]
